FROM php:7.4.4-apache

RUN apt-get update

RUN apt-get install -y \ 
    git \
    zip \
    curl \
    sudo \
    nano \
    unzip \
    libicu-dev \
    libbz2-dev \
    libpng-dev \ 
    libjpeg-dev \
    libreadline-dev \
    libfreetype6-dev \
    libonig-dev \
    libzip-dev \
    g++


# definindo variaveis de ambiente 
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public

# alterando diretorio padrao de inicialização do apache
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# ativando 
RUN a2enmod rewrite headers

# renomeando aquivo php.ini-development para php.ini
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

# extenções
RUN docker-php-ext-install \
    bz2 \
    intl \
    iconv \
    bcmath \
    opcache \
    calendar \
    mbstring \
    pdo_mysql \
    zip

RUN chmod -R 777 /var/www/html

#instalaçaõ do composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# instalação do laravel
RUN composer global require laravel/installer
RUN export PATH="$PATH:$HOME/.composer/vendor/bin"
RUN echo 'export PATH="$PATH:$HOME/.composer/vendor/bin"' >> ~/.bashrc
